CIRCUITPY_WIFI_SSID = "NotGoodButGoodEnough"
CIRCUITPY_WIFI_PASSWORD = "strongcell751"

LOCATION = "Missoula, MT"
LATITUDE = "46.873024"
LONGITUDE = "-113.979844"
TIMEZONE = "US/Mountain"
TIMEZONE_OFFSET = -6
MEASUREMENT_UNITS = "IMPERIAL"